// Package version carries the release version.
//
// Generated by scripts/sync-version.sh from the VERSION file. Do not edit.
// Run `make version-sync` after bumping VERSION.
package version

// Current is the release this binary was built from.
const Current = "0.5.1"
