#!/usr/bin/env bash
# Regenerate the per-language version constants from the VERSION file.
#
# VERSION is the single source of truth. The generated files are COMMITTED
# rather than produced at build time, because the Homebrew formula builds
# from a source tarball with no git metadata and invokes `swift build` /
# `go build` directly — anything the Makefile computed would be absent
# there. Committing them keeps all three build paths (make, Homebrew, CI)
# reporting the same string.
#
#   sync-version.sh            rewrite the constants from VERSION
#   sync-version.sh --check    exit 1 if the committed constants differ
#
# `--check` must never write to the tracked files: a guard that repairs
# the drift it is meant to detect always passes.
set -euo pipefail

cd "$(dirname "$0")/.."
VERSION="$(tr -d '[:space:]' < VERSION)"

if [ -z "$VERSION" ]; then
  echo "VERSION file is empty" >&2
  exit 1
fi

SWIFT_FILE="daemon/Sources/StenoDaemon/Version.swift"
GO_FILE="cmd/steno/internal/version/version.go"

swift_contents() {
  cat <<EOF
// Generated by scripts/sync-version.sh from the VERSION file. Do not edit.
// Run \`make version-sync\` after bumping VERSION.

enum StenoVersion {
    static let current = "$VERSION"
}
EOF
}

go_contents() {
  cat <<EOF
// Package version carries the release version.
//
// Generated by scripts/sync-version.sh from the VERSION file. Do not edit.
// Run \`make version-sync\` after bumping VERSION.
package version

// Current is the release this binary was built from.
const Current = "$VERSION"
EOF
}

if [ "${1:-}" = "--check" ]; then
  status=0
  for pair in "$SWIFT_FILE:swift_contents" "$GO_FILE:go_contents"; do
    file="${pair%%:*}"
    fn="${pair##*:}"
    if [ ! -f "$file" ]; then
      echo "MISSING: $file" >&2
      status=1
      continue
    fi
    if ! "$fn" | diff -u "$file" - > /dev/null; then
      echo "DRIFTED: $file does not match VERSION ($VERSION)" >&2
      "$fn" | diff -u "$file" - >&2 || true
      status=1
    fi
  done
  if [ "$status" -ne 0 ]; then
    echo "" >&2
    echo "Run \`make version-sync\` and commit the result." >&2
    exit 1
  fi
  echo "Version constants match VERSION ($VERSION)"
  exit 0
fi

swift_contents > "$SWIFT_FILE"
go_contents > "$GO_FILE"
echo "version synced to $VERSION"
